# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2016-08-04T07:57:11Z
  generation: 2
  labels:
    run: test-ingress-node-1
  name: test-ingress-node-1
  namespace: default
  resourceVersion: "138760"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/test-ingress-node-1
  uid: 0cbcad95-5a19-11e6-a3f0-42010af0011b
spec:
  replicas: 1
  selector:
    matchLabels:
      run: test-ingress-node-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: test-ingress-node-1
    spec:
      containers:
      - image: gcr.io/altai-pro/test-ingress
        imagePullPolicy: Always
        name: test-ingress-node-1
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
